# Generated by Django 3.2.8 on 2021-10-28 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0002_advisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='photo',
            field=models.ImageField(max_length=255, upload_to='pictures/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='callsBooked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.CharField(max_length=50)),
                ('adv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solution.advisor')),
            ],
        ),
    ]
