# Generated by Django 3.2.8 on 2021-10-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0003_auto_20211028_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='photo',
            field=models.ImageField(max_length=255, upload_to='static'),
        ),
    ]
